import { test } from 'node:test';
import assert from 'node:assert/strict';
import { projectSavings } from './projection.ts';
const base = { startingBalance: 10000, monthlyContribution: 100, years: 2, annualReturn: 0 };
const near = (a: number, b: number) => assert.ok(Math.abs(a-b) <= Math.max(1,Math.abs(b))*1e-10, `${a} != ${b}`);
test('zero return and annual snapshots', () => { const rows=projectSavings(base); assert.equal(rows.length,3); assert.deepEqual(rows.at(-1),{year:2,balance:12400,invested:12400,growth:0}); });
test('zero horizon includes only the initial balance', () => assert.deepEqual(projectSavings({...base,years:0}),[{year:0,balance:10000,invested:10000,growth:0}]));
test('effective annual return compounds correctly', () => near(projectSavings({...base,monthlyContribution:0,years:1,annualReturn:10}).at(-1)!.balance,11000));
test('negative growth is preserved', () => {const last=projectSavings({...base,monthlyContribution:0,annualReturn:-20}).at(-1)!;near(last.balance,6400);near(last.growth,-3600);});
test('end-of-month contribution timing, independently calculated', () => near(projectSavings({...base,startingBalance:1000,years:1,annualReturn:12.68250301319698}).at(-1)!.balance,2395.075331451668));
test('minus 99 percent boundary', () => near(projectSavings({...base,monthlyContribution:0,years:1,annualReturn:-99}).at(-1)!.balance,100));
test('all zero amounts remain zero', () => assert.ok(projectSavings({...base,startingBalance:0,monthlyContribution:0,years:80,annualReturn:30}).every(row=>row.balance===0)));
test('upper supported bounds remain finite', () => assert.ok(projectSavings({startingBalance:1e9,monthlyContribution:1e7,years:80,annualReturn:30}).every(row=>Number.isFinite(row.balance))));
test('rejects invalid input', () => {for(const patch of [{years:1.5},{years:-1},{years:81},{annualReturn:-100},{annualReturn:31},{startingBalance:-1},{startingBalance:1e10},{monthlyContribution:-1},{monthlyContribution:1e8},{startingBalance:NaN},{annualReturn:Infinity}]) assert.throws(()=>projectSavings({...base,...patch}),RangeError);});
test('matches closed form at a long horizon', () => {const r=Math.expm1(Math.log1p(.07)/12),n=360;const expected=50000*Math.pow(1+r,n)+500*Math.expm1(n*Math.log1p(r))/r;near(projectSavings({startingBalance:50000,monthlyContribution:500,years:30,annualReturn:7}).at(-1)!.balance,expected);});
